Feature/spotify set up
SoundSurf/backend pull request #10
Opened 2024-04-15 11:17 UTC by zkxmdkdltm

2024-04-15 11:37 UTC, roganOhDev requested changes

2024-04-15 11:37 UTC, roganOhDev commented on build.gradle
> +        maven { url 'https://jitpack.io' }
우리 그래들인데 그래들로 표현해주세용

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/controller/SpotifyController.java
> +    public List<MusicDto.Common.Response> search(
리턴할때 리스트는 dto 안으로 집어넣어주세요

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/controller/SpotifyController.java
> +    public List<MusicDto.Common.Response> recommendation(
dto

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +    public List<MusicDto.Common.Response> search(MusicDto.Search.Request request) throws IOException, ParseException, SpotifyWebApiException {
exception handling 해주세용

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +            List<String> images = Stream.of(track.getAlbum().getImages())
final var

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +            trackDtos.add(new MusicDto.Common.Response(
track 만 넘기고 메서드 안에서 처리하는건 어때요?

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +            if (track.getPreviewUrl() == null) continue;
이거 함수로 빼주세요.
'각 트랙마다 ~을 한다' 로 한줄로 정의가 가능하니깐요

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +            if (track.getPreviewUrl() == null) continue;
역시 여기도요

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +            if (track.getPreviewUrl() == null) continue;
url 이 널인거랑 곡이랑은 상관 없는거같아요. 그냥 널로 넘겨도 될거같은데요?

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +        for (TrackSimplified track : tracks) {
이 for 문 위에서도 본거같은데 더더욱 추출해야겠네요

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +                    .collect(Collectors.toList());
toUnmodifiableList 로 해주세요.
그거가 합쳐진게 `.toList()` 입니다

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyTokenProvider.java
> +            System.out.println("Error: " + e.getMessage());
sout 해버리면 확인이 불가능해요. apiException 던지고, 에러 로그를 찍어주세요

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/dto/MusicDto.java
> +            private String title;
조건이 있을텐데요? 낫 널이라던가 최대 글자수라던가

2024-04-15 11:37 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyTokenProvider.java
> +            log.info("Access token: " + clientCredentials.getAccessToken());
이렇게하면 토큰 두번가져오는거 아녜요?

2024-04-15 11:37 UTC, roganOhDev commented
고생하셨어욤~

2024-04-16 01:14 UTC, zkxmdkdltm commented on build.gradle
> +        maven { url 'https://jitpack.io' }
https://github.com/spotify-web-api-java/spotify-web-api-java?tab=readme-ov-file#Documentation

공식 문서에 그래들은 저렇게 하라고 나와있음당

2024-04-16 01:16 UTC, zkxmdkdltm commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +            if (track.getPreviewUrl() == null) continue;
url 없는건 재생을 못 시켜서 우선 null일시에는 넘기는걸로 처리 해뒀습니다.

2024-04-16 01:17 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +            if (track.getPreviewUrl() == null) continue;
잘못봤네요 ㅎㅎ 썸네일 url 로 봤어요

2024-04-16 08:09 UTC, roganOhDev requested changes

2024-04-16 08:09 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/controller/SpotifyController.java
> +            @Valid @RequestBody MusicDto.Search.Request request) throws IOException, ParseException, SpotifyWebApiException {
던지지 않는 익셉션은 지워주세용

2024-04-16 08:09 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyService.java
> +    public MusicDto.Common.Response search(MusicDto.Search.Request request) {
파라미터들 final 써주세요

2024-04-16 08:09 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/dto/MusicDto.java
> +                        Arrays.asList(track.getArtists()).stream().map(artist -> artist.getName()).toList(),
(어레이).stream() 이 바로 가능합니다~

2024-04-16 08:09 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/dto/MusicDto.java
> +                        Arrays.asList(track.getArtists()).stream().map(artist -> artist.getName()).toList(),
artist.getName() 에서 아마 저거 메서드 하나만 써서 `::getName` 으로 바꿀 수 있을껄요?

2024-04-16 08:09 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/dto/MusicDto.java
> +                        Arrays.asList(track.getArtists()).stream().map(artist -> artist.getName()).toList(),
요기도 asList 지워주세용

2024-04-16 08:09 UTC, roganOhDev commented on src/main/java/com/api/soundsurf/iam/domain/SpotifyTokenProvider.java
> +            log.info("Error: " + e.getMessage());
`log.error() ` 를 사용해주세요

2024-04-17 07:19 UTC, roganOhDev approved these changes

2024-04-17 07:49 UTC, merged